config/routes.rb
Rails.application.routes.draw do

  resources :mod_tours
  resources :events
  resources :calendars
  resources :event_categories
  resources :rooms
  get 'pages/about'

  get 'pages/terms'

  get 'pages/tour'

  get 'pages/plans'

  resources :studios 

  namespace :studios do 
    post 'get_by_name'
  end  

  get 'home/index'

  get 'home/about'

  get 'home/terms'
  
  root :to => 'home#index'
  
  resources :user_plan_months
  resources :user_plans
  resources :plan_mods
  resources :plans
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  resources :category_mods
  resources :icons
  resources :mods

  resources :studio_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	belongs_to :room
	has_many :events
end

app/models/category_event.rb
class CategoryEvent < ApplicationRecord
end

app/models/category_mod.rb
class CategoryMod < ApplicationRecord
	has_many :mods
	belongs_to :icon
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	belongs_to :calendar
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
end

app/models/icon.rb
class Icon < ApplicationRecord
	has_many :mods
	has_many :category_mods
end

app/models/mod.rb
class Mod < ApplicationRecord
	belongs_to :icon
	belongs_to :category_mod
 	has_and_belongs_to_many :plans
end

app/models/mod_tour.rb
class ModTour < ApplicationRecord
	belongs_to :mod
end

app/models/plan.rb
class Plan < ApplicationRecord
   belongs_to :icon
   has_and_belongs_to_many :mods
end

app/models/plan_mod.rb
class PlanMod < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :studio
	has_many :calendars
end

app/models/studio.rb
class Studio < ApplicationRecord
	# belongs_to :user
	has_many :rooms
	validates_presence_of :name
	validates_presence_of :cnpj
 	validates_presence_of :email

	def self.search(search)
	  search = "%#{search}%"
	  where("name ILIKE ?", search)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plans
  
  validates :name, :presence => true
  validates :surname, :presence => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_plan.rb
class UserPlan < ApplicationRecord
	belongs_to :plan
	belongs_to :user
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  before_action :set_event_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /event_categories
  # GET /event_categories.json
  def index
    @event_categories = EventCategory.all
  end

  # GET /event_categories/1
  # GET /event_categories/1.json
  def show
  end

  # GET /event_categories/new
  def new
    @event_category = EventCategory.new
  end

  # GET /event_categories/1/edit
  def edit
  end

  # POST /event_categories
  # POST /event_categories.json
  def create
    @event_category = EventCategory.new(event_category_params)

    respond_to do |format|
      if @event_category.save
        format.html { redirect_to @event_category, notice: 'Event category was successfully created.' }
        format.json { render :show, status: :created, location: @event_category }
      else
        format.html { render :new }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_categories/1
  # PATCH/PUT /event_categories/1.json
  def update
    respond_to do |format|
      if @event_category.update(event_category_params)
        format.html { redirect_to @event_category, notice: 'Event category was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_category }
      else
        format.html { render :edit }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_categories/1
  # DELETE /event_categories/1.json
  def destroy
    @event_category.destroy
    respond_to do |format|
      format.html { redirect_to event_categories_url, notice: 'Event category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_category
      @event_category = EventCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_category_params
      params.require(:event_category).permit(:name, :description, :icon_id)
    end
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/event_categories/_form.html.erb
<%= form_with(model: event_category, local: true) do |form| %>
  <% if event_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_category.errors.count, "error") %> prohibited this event_category from being saved:</h2>

      <ul>
      <% event_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_category_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :event_category_description %>
  </div>

  <div class="field">
    <%= form.label :icon_id %>
    <%= form.number_field :icon_id, id: :event_category_icon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_categories/edit.html.erb
<h1>Editing Event Category</h1>

<%= render 'form', event_category: @event_category %>

<%= link_to 'Show', @event_category %> |
<%= link_to 'Back', event_categories_path %>

app/views/event_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_categories.each do |event_category| %>
      <tr>
        <td><%= event_category.name %></td>
        <td><%= event_category.description %></td>
        <td><%= event_category.icon_id %></td>
        <td><%= link_to 'Show', event_category %></td>
        <td><%= link_to 'Edit', edit_event_category_path(event_category) %></td>
        <td><%= link_to 'Destroy', event_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Category', new_event_category_path %>

app/views/event_categories/new.html.erb
<h1>New Event Category</h1>

<%= render 'form', event_category: @event_category %>

<%= link_to 'Back', event_categories_path %>

app/views/event_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event_category.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @event_category.icon_id %>
</p>

<%= link_to 'Edit', edit_event_category_path(@event_category) %> |
<%= link_to 'Back', event_categories_path %>