config/routes.rb
Rails.application.routes.draw do

  resources :mod_tours
  resources :events
  resources :calendars
  resources :event_categories
  resources :rooms
  get 'pages/about'

  get 'pages/terms'

  get 'pages/tour'

  get 'pages/plans'

  resources :studios 

  namespace :studios do 
    post 'get_by_name'
  end  

  get 'home/index'

  get 'home/about'

  get 'home/terms'
  
  root :to => 'home#index'
  
  resources :user_plan_months
  resources :user_plans
  resources :plan_mods
  resources :plans
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  resources :category_mods
  resources :icons
  resources :mods

  resources :studio_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	belongs_to :room
	has_many :events
end

app/models/category_event.rb
class CategoryEvent < ApplicationRecord
end

app/models/category_mod.rb
class CategoryMod < ApplicationRecord
	has_many :mods
	belongs_to :icon
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	belongs_to :calendar
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
end

app/models/icon.rb
class Icon < ApplicationRecord
	has_many :mods
	has_many :category_mods
end

app/models/mod.rb
class Mod < ApplicationRecord
	belongs_to :icon
	belongs_to :category_mod
 	has_and_belongs_to_many :plans
end

app/models/mod_tour.rb
class ModTour < ApplicationRecord
	belongs_to :mod
end

app/models/plan.rb
class Plan < ApplicationRecord
   belongs_to :icon
   has_and_belongs_to_many :mods
end

app/models/plan_mod.rb
class PlanMod < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :studio
	has_many :calendars
end

app/models/studio.rb
class Studio < ApplicationRecord
	# belongs_to :user
	has_many :rooms
	validates_presence_of :name
	validates_presence_of :cnpj
 	validates_presence_of :email

	def self.search(search)
	  search = "%#{search}%"
	  where("name ILIKE ?", search)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plans
  
  validates :name, :presence => true
  validates :surname, :presence => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_plan.rb
class UserPlan < ApplicationRecord
	belongs_to :plan
	belongs_to :user
end

app/controllers/plan_mods_controller.rb
class PlanModsController < ApplicationController
  before_action :set_plan_mod, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /plan_mods
  # GET /plan_mods.json
  def index
    @plan_mods = PlanMod.all
    @mod_title = "Planos de Usuários"
  end

  # GET /plan_mods/1
  # GET /plan_mods/1.json
  def show
  end

  # GET /plan_mods/new
  def new
    @plan_mod = PlanMod.new
    @mod_title = "<a href='/user_plans'>Planos de Usuários</a> ><span>Editar Plano de Usuário</span>"
  end

  # GET /plan_mods/1/edit
  def edit
  end

  # POST /plan_mods
  # POST /plan_mods.json
  def create
    @plan_mod = PlanMod.new(plan_mod_params)

    respond_to do |format|
      if @plan_mod.save
        format.html { redirect_to @plan_mod, notice: 'Plan mod was successfully created.' }
        format.json { render :show, status: :created, location: @plan_mod }
      else
        format.html { render :new }
        format.json { render json: @plan_mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plan_mods/1
  # PATCH/PUT /plan_mods/1.json
  def update
    respond_to do |format|
      if @plan_mod.update(plan_mod_params)
        format.html { redirect_to @plan_mod, notice: 'Plan mod was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan_mod }
      else
        format.html { render :edit }
        format.json { render json: @plan_mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plan_mods/1
  # DELETE /plan_mods/1.json
  def destroy
    @plan_mod.destroy
    respond_to do |format|
      format.html { redirect_to plan_mods_url, notice: 'Plan mod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan_mod
      @plan_mod = PlanMod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_mod_params
      params.require(:plan_mod).permit(:plan_id, :mod_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plan_mods_helper.rb
module PlanModsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/plan_mods/_form.html.erb
<%= form_with(model: plan_mod, local: true) do |form| %>
  <% if plan_mod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan_mod.errors.count, "error") %> prohibited this plan_mod from being saved:</h2>

      <ul>
      <% plan_mod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :plan_id %>
    <%= form.number_field :plan_id, id: :plan_mod_plan_id %>
  </div>

  <div class="field">
    <%= form.label :mod_id %>
    <%= form.number_field :mod_id, id: :plan_mod_mod_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plan_mods/edit.html.erb
<h1>Editing Plan Mod</h1>

<%= render 'form', plan_mod: @plan_mod %>

<%= link_to 'Show', @plan_mod %> |
<%= link_to 'Back', plan_mods_path %>

app/views/plan_mods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plan Mods</h1>

<table>
  <thead>
    <tr>
      <th>Plan</th>
      <th>Mod</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plan_mods.each do |plan_mod| %>
      <tr>
        <td><%= plan_mod.plan_id %></td>
        <td><%= plan_mod.mod_id %></td>
        <td><%= link_to 'Show', plan_mod %></td>
        <td><%= link_to 'Edit', edit_plan_mod_path(plan_mod) %></td>
        <td><%= link_to 'Destroy', plan_mod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan Mod', new_plan_mod_path %>

app/views/plan_mods/new.html.erb
<h1>New Plan Mod</h1>

<%= render 'form', plan_mod: @plan_mod %>

<%= link_to 'Back', plan_mods_path %>

app/views/plan_mods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan:</strong>
  <%= @plan_mod.plan_id %>
</p>

<p>
  <strong>Mod:</strong>
  <%= @plan_mod.mod_id %>
</p>

<%= link_to 'Edit', edit_plan_mod_path(@plan_mod) %> |
<%= link_to 'Back', plan_mods_path %>