config/routes.rb
Rails.application.routes.draw do

  resources :mod_tours
  resources :events
  resources :calendars
  resources :event_categories
  resources :rooms
  get 'pages/about'

  get 'pages/terms'

  get 'pages/tour'

  get 'pages/plans'

  resources :studios 

  namespace :studios do 
    post 'get_by_name'
  end  

  get 'home/index'

  get 'home/about'

  get 'home/terms'
  
  root :to => 'home#index'
  
  resources :user_plan_months
  resources :user_plans
  resources :plan_mods
  resources :plans
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  resources :category_mods
  resources :icons
  resources :mods

  resources :studio_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	belongs_to :room
	has_many :events
end

app/models/category_event.rb
class CategoryEvent < ApplicationRecord
end

app/models/category_mod.rb
class CategoryMod < ApplicationRecord
	has_many :mods
	belongs_to :icon
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	belongs_to :calendar
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
end

app/models/icon.rb
class Icon < ApplicationRecord
	has_many :mods
	has_many :category_mods
end

app/models/mod.rb
class Mod < ApplicationRecord
	belongs_to :icon
	belongs_to :category_mod
 	has_and_belongs_to_many :plans
end

app/models/mod_tour.rb
class ModTour < ApplicationRecord
	belongs_to :mod
end

app/models/plan.rb
class Plan < ApplicationRecord
   belongs_to :icon
   has_and_belongs_to_many :mods
end

app/models/plan_mod.rb
class PlanMod < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :studio
	has_many :calendars
end

app/models/studio.rb
class Studio < ApplicationRecord
	# belongs_to :user
	has_many :rooms
	validates_presence_of :name
	validates_presence_of :cnpj
 	validates_presence_of :email

	def self.search(search)
	  search = "%#{search}%"
	  where("name ILIKE ?", search)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plans
  
  validates :name, :presence => true
  validates :surname, :presence => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_plan.rb
class UserPlan < ApplicationRecord
	belongs_to :plan
	belongs_to :user
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :studio_id, :picture, :description, :price_hour, :price_weekend, :price_late, :category_event)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_name %>
  </div>

  <div class="field">
    <%= form.label :studio_id %>
    <%= form.number_field :studio_id, id: :room_studio_id %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :room_picture %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :room_description %>
  </div>

  <div class="field">
    <%= form.label :price_hour %>
    <%= form.text_field :price_hour, id: :room_price_hour %>
  </div>

  <div class="field">
    <%= form.label :price_weekend %>
    <%= form.text_field :price_weekend, id: :room_price_weekend %>
  </div>

  <div class="field">
    <%= form.label :price_late %>
    <%= form.text_field :price_late, id: :room_price_late %>
  </div>

  <div class="field">
    <%= form.label :category_event %>
    <%= form.number_field :category_event, id: :room_category_event %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Studio</th>
      <th>Picture</th>
      <th>Description</th>
      <th>Price hour</th>
      <th>Price weekend</th>
      <th>Price late</th>
      <th>Category event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.studio_id %></td>
        <td><%= room.picture %></td>
        <td><%= room.description %></td>
        <td><%= room.price_hour %></td>
        <td><%= room.price_weekend %></td>
        <td><%= room.price_late %></td>
        <td><%= room.category_event %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Studio:</strong>
  <%= @room.studio_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @room.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price hour:</strong>
  <%= @room.price_hour %>
</p>

<p>
  <strong>Price weekend:</strong>
  <%= @room.price_weekend %>
</p>

<p>
  <strong>Price late:</strong>
  <%= @room.price_late %>
</p>

<p>
  <strong>Category event:</strong>
  <%= @room.category_event %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>