config/routes.rb
Rails.application.routes.draw do

  resources :mod_tours
  resources :events
  resources :calendars
  resources :event_categories
  resources :rooms
  get 'pages/about'

  get 'pages/terms'

  get 'pages/tour'

  get 'pages/plans'

  resources :studios 

  namespace :studios do 
    post 'get_by_name'
  end  

  get 'home/index'

  get 'home/about'

  get 'home/terms'
  
  root :to => 'home#index'
  
  resources :user_plan_months
  resources :user_plans
  resources :plan_mods
  resources :plans
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  resources :category_mods
  resources :icons
  resources :mods

  resources :studio_steps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
	belongs_to :room
	has_many :events
end

app/models/category_event.rb
class CategoryEvent < ApplicationRecord
end

app/models/category_mod.rb
class CategoryMod < ApplicationRecord
	has_many :mods
	belongs_to :icon
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	belongs_to :calendar
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
end

app/models/icon.rb
class Icon < ApplicationRecord
	has_many :mods
	has_many :category_mods
end

app/models/mod.rb
class Mod < ApplicationRecord
	belongs_to :icon
	belongs_to :category_mod
 	has_and_belongs_to_many :plans
end

app/models/mod_tour.rb
class ModTour < ApplicationRecord
	belongs_to :mod
end

app/models/plan.rb
class Plan < ApplicationRecord
   belongs_to :icon
   has_and_belongs_to_many :mods
end

app/models/plan_mod.rb
class PlanMod < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :studio
	has_many :calendars
end

app/models/studio.rb
class Studio < ApplicationRecord
	# belongs_to :user
	has_many :rooms
	validates_presence_of :name
	validates_presence_of :cnpj
 	validates_presence_of :email

	def self.search(search)
	  search = "%#{search}%"
	  where("name ILIKE ?", search)
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plans
  
  validates :name, :presence => true
  validates :surname, :presence => true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_plan.rb
class UserPlan < ApplicationRecord
	belongs_to :plan
	belongs_to :user
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: [:show, :edit, :update, :destroy]
  layout :set_layout
  before_action :set_mod
  # before_action :authenticate_user!
  $mod_title = "Estúdios"

  # GET /studios
  # GET /studios.json
  def index
    @studios = Studio.all
    @mod_title = $mod_title
  end

  # GET /studios/1
  # GET /studios/1.json
  def show
  end

  # GET /studios/new
  def new
    @studio = Studio.new
    @mod_title = "<a href='/studios'>#{$mod_title}</a> ><span>Incluir Estúdio</span>" 
  end

  def get_by_name
    # @studio = Studio.search(params[:name])
    respond_to do |format|
      format.js 
    end
  end

  # GET /studios/1/edit
  def edit
  end

  # POST /studios
  # POST /studios.json
  def create
    @studio = Studio.new(studio_params)

    if @studio.save
      session[:studio_id] = @studio.id
      redirect_to studio_steps_path 
    else
      render :new
    end

  end

  # PATCH/PUT /studios/1
  # PATCH/PUT /studios/1.json
  def update
    respond_to do |format|
      if @studio.update(studio_params)
        session[:studio_id] = @studio.id
        format.html { redirect_to studio_steps_path, notice: 'Studio was successfully updated.' }
        format.json { render :show, status: :ok, location: @studio }
      else
        format.html { render :edit }
        format.json { render json: @studio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studios/1
  # DELETE /studios/1.json
  def destroy
    @studio.destroy
    respond_to do |format|
      format.html { redirect_to studios_url, notice: 'Studio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_layout
      case action_name
      when "index"
        "layout_banner"
      else
        "application"
      end
    end

    def set_mod
      @mod = Mod.find_by(slug: "studios")  
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_studio
      # @studio = Studio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studio_params
      params.require(:studio).permit(:name, :social_name, :cnpj, :email, :description, :user_id, :cep, :address, :city, :uf, :picture, :open_at, :close_at, :telephone, :celphone, :facebook, :instagram, :site, :n, :ngb)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/views/studios/_form.html.erb
<%= form_with(model: studio, local: true) do |form| %>
  <% if studio.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(studio.errors.count, "error") %> erros ao salvar estúdio:</h5>
      <ul>
      <% studio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label "Nome *" %>
    <%= form.text_field :name, id: :studio_name, class: 'required' %>
  </div>

  <div class="input-field">
    <%= form.label "CNPJ *" %>
    <%= form.text_field :cnpj, id: :studio_cnpj, class: 'required cnpj' %>
  </div> 

  <div class="input-field">
    <%= form.label "email *" %>
    <%= form.email_field :email, id: :studio_email, class: 'required email' %>
  </div>

  <div class="input-field">
    <%= form.label "descrição" %>
    <%= form.text_area :description, class: 'materialize-textarea', id: :studio_description %>
  </div>

  <div class="row">
    <div class="col m2 offset-m9">
      <div class=" input-field">
        <%= form.submit "Salvar e próximo", disabled:true, class: 'btn blue waves-effects waves-light' %>
      </div>
    </div>
  </div>

<% end %>

app/views/studios/edit.html.erb
<h1>Editing Studio</h1>

<%= render 'form', studio: @studio %>

<%= link_to 'Show', @studio %> |
<%= link_to 'Back', studios_path %>

app/views/studios/get_by_name.js.erb
<% if @studio %> 
	console.log("já existe um estúdio com esse nome");
<% else %>
	console.log("Ok!");
<% end %>

app/views/studios/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  
  <div class="col m3 s12">
    <div class="card">
      <%= link_to new_studio_path do %>
        <div class="card-image waves-effect waves-block waves-light">
          <span class="card-title activator grey-text text-darken-4 text-center"></span>
          <p class="text-center"><i class="material-icons i_center">playlist_add</i> <BR>Cadastrar Estúdio</p>
        </div>
      <% end %>
    </div>      
  </div>

  <% @studios.each do |studio| %>
    <div class="col m3 s12">
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="images/office.jpg">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= studio.name %><i class="material-icons right">more_vert</i></span>
          <p><a href="#">This is a link</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Informações<i class="material-icons right">close</i></span>
          <p><%= link_to 'Show', studio %></p>
          <p><%= link_to 'Edit', edit_studio_path(studio) %></p>
          <p><%= link_to 'Destroy', studio, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>  

app/views/studios/new.html.erb
<h5>Cadastro de Estúdio</h5>
<%= render 'form', studio: @studio %>

app/views/studios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @studio.name %>
</p>

<p>
  <strong>Social name:</strong>
  <%= @studio.social_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @studio.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @studio.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @studio.user_id %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @studio.cep %>
</p>

<p>
  <strong>Address:</strong>
  <%= @studio.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @studio.city %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @studio.uf %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @studio.picture %>
</p>

<%= link_to 'Edit', edit_studio_path(@studio) %> |
<%= link_to 'Back', studios_path %>